### PR TITLE
cache `project-root` calls for all breadcrumb buffers

### PR DESCRIPTION
**Pull request by jmpunkt**
## Issue
Breadcrumbs calls `project-root` on every refresh/redraw, causing slow text cursor movement on my NixOS system under certain circumstances.

For files which do no have a project root and are located in a directory which contains a lot of other directories, the `project-root` call is not cheap. Resulting in delayed text cursor moving.

This is most noticeable with distros  like NixOS. They store all of their files in a single flat directory. So there are many directories located in `/nix/store`. Browsing any file located in this directory is slow when using breadcrumb, since the `project-root` iterates over all files in these directories.

## Fix
Cache the project root for every buffer where breadcrumb is enabled. When the buffer gets destroyed or reverted, we remove the entry from our cache.

## Downsides
There is currently now way to detect if a file has gotten a project root recently. As a result, breadcrumbs might display wrong data. However, the performance gains outweigh these downs sides (imo). The user can always force refresh the buffer by killing or reverting it.

### CODE REVIEW

**Comment by joaotavora** [comment]
This seems to be a duplicate of #18, where I proposed that this caching be added to project.el itself.  If I recall correctly, in many situations there is some sort of project.el cache, but project.el doesn't "want" to cache the _absence_ of a project root, and that's a problem.  So the idea of an expiring cache was introduced, but it hasn't materialized yet (FWIW I don't think it should materialize in breadcrumb)

See https://github.com/joaotavora/breadcrumb/issues/18#issuecomment-2243919858 specifically.

**Comment by jmpunkt** [comment]
Thanks for the response. My guess is, there will never be a proper cache in project.el. Maintaining a valid cache is hard. Providing the user with false information due to caching on the project.el level seems too risky. I think the downstream packages which depend on the project.el must decide if the need caching. They can also decide the cache functionality based on their needs and cut corners if needed. For example, it is not a huge problem if breadcrumb displays invalid information. You might see a wrong breadcrumb for while, if the project root changes. But breadcrumb only displays additional information and does not rely on the correctness. Other packages might rely on the correct project root to function properly.

**Comment by joaotavora** [comment]
> Providing the user with false information due to caching on the project.el level seems too risky.

I don't see why exactly. What risks do you foresee that are somehow more dramatic than wrong breadcrumbs?

Anyway project.el already caches the root, it just doesn't cache the _absence_ of a root.  You're hitting that corner case with your setup (I never hit it, but I use a more normal linux I guess).

The reason it doesn't cache the absence of root is that it's thought to be more common that someone adds a roots (via `git init` for example) then removes the root (via `rm -rf .git`).  Maybe that's true, But both are definitely possible.  And both are definitely infrequent when compared to the frequency of lookups.  So I personally see these worries as a bit premature.

```
(defun project-try-vc (dir)
  ;; FIXME: Learn to invalidate when the value changes:
  ;; `project-vc-merge-submodules' or `project-vc-extra-root-markers'.
  (or (vc-file-getprop dir 'project-vc)
      ;; FIXME: Cache for a shorter time.
      (let ((res (project-try-vc--search dir)))
        (and res (vc-file-setprop dir 'project-vc res))
        res)))
```

IMHO caching the absence of a root as well and providing a manual invalidation operation (or perhaps hooking it to revert-buffer). would be fine.  Also I think I would cache per buffer, not per directory (is the latter just to save space?). Anyway here's pinging @dgutov project.el maintainer.  

I don't contribute to Emacs proper much anymore. I think the timed cache-the-absence idea could be done in `project.el`, maybe set it to some reasonable value like 10s or so.  

But if it's not in the stars and you can implement this timed cache-the-absence specifically for breadcrumb, go ahead and I'll merge it.

**Comment by jmpunkt** [comment]
> I don't see why exactly. What risks do you foresee that are somehow more dramatic than wrong breadcrumbs?

I was thinking about something commands like `project-eshell`. For example, you generate yourself some project files and open these files. Then you notice, that you have not created a Git repo. All existing buffers have to be re-loaded. Otherwise your `project-eshell` command would always ask for a project. However, these event are extremely rare compared to normal workflow. Compared to breadcrumb, it would display a not so correct file path which does not interrupt my workflow so drastically. These things are not life threatening, but I would argue that one is more annoying than the other.

Time based caches would improve the situation with my setup, but I think it would not fix it. Every time the cache is invalidated, it has to traverse the directories again. Resulting in occasional stutters which are annoying.

I will explore some options regarding `filenotify`. It is a unified file notify interface inside Emacs. This would be the best way to keep the cache synced with the file system. These change would probably be best in the `project.el`.

For now I will close this while I explore the other options. Thanks for the feedback and your time.

**Comment by joaotavora** [comment]
> Time based caches would improve the situation with my setup, but I think it would not fix it. Every time the cache is invalidated, it has to traverse the directories again. Resulting in occasional stutters which are annoying.

Yeah, cache invalidation is one of the "two hard problems" along with naming things, and off-by-one errors :-)

Here I think caching greedingly (_including_ the absence scenario) and requiring manual invalidation is the best choice.  
it's exactly what you were proposing:

> The user can always force refresh the buffer by killing or reverting it.

I just happen to think it should be done in `project.el`.  Maybe, if one size doesn't really fit all, maybe the extension could inform project of what caching policies to consider at the time of calling `project-current`, vi a new argument or via some dynamic variable.

I don't thing `filenotify` is going to be very elegant as it's bound to be (very) complicated and not even general as there are ways to setup project-find-functions elements that compute projects that have nothing to do with marker files.

**Pull request closed without merging**
